<?php

function program_menu() {
	$items['programs'] = array(
	  'title' => 'programs',
	  'page callback' => 'program_search',
	  'access arguments' => array('access content'),
	);

	return $items;
}

function program_search() {
	$program_module_path = drupal_get_path('module', 'program');
	
	drupal_add_js($program_module_path .'/js/libs/list.js', array('scope'=>'footer') );
  drupal_add_js($program_module_path .'/js/libs/list.pagination.js', array('scope'=>'footer') );
  drupal_add_js($program_module_path .'/js/libs/underscore.js', array('scope'=>'footer') );
  drupal_add_js($program_module_path .'/js/api.js', array('scope'=>'footer') );
	drupal_add_js($program_module_path .'/js/program.js', array('scope'=>'footer'));
	drupal_add_css(
		$program_module_path . '/program.css', 
		array('group' => CSS_DEFAULT, 'type' => 'file')
	);
  return array('#markup' => '
  	<div id="programs">
        <input class="search" placeholder="Search"/>
        <div class="catagories">
          <button class="sort" data-sort="title">
            Sort by title
          </button>
          <button class="sort" data-sort="country">
            Sort by country
          </button>
        </div>
        <ul class="list">
        </ul>
        <br />
        <!-- results: -->
        <!-- <ul class="pag-nav">
          <li id="first"><a><</a></li>
          <li id="last"><a>></a></li>
        </ul> -->
        <ul class="pagination"> 
        </ul>
      </div>
  ');
} 


