<?php

include 'utilityFucntions.php';

function program_menu() {
	$items['programs'] = array(
	  'title' => 'programs',
	  'page callback' => 'program_search',
	  'access arguments' => array('access content'),
	);

	return $items;
}

function program_search() {
  $program_module_path = drupal_get_path('module', 'program');
  
  loadjs(array(
      '/js/libs/listjs/dist/list.js',
      '/js/libs/listjs/list.pagination.js',
      '/js/libs/underscore.js',
      'js/libs/jquery.sticky-kit.js',
      '/js/api.js',
      '/js/program.js'
  ));

  loadcss(array(
    '/program.css'
  ));

  return array('#markup' => '

  	<div id="programs">
        <input class="search" placeholder="Where do you want to study?"/>
        <button class="sort" data-sort="title">
          search
        </button>
        <div class="catagories">
        filter by:
        ' . selectFrom('discipline')
          .selectFrom('term') 
        .'
        </div>
        <ul class="list">
        </ul>
        <br />
        <!-- results: -->
        <!-- <ul class="pag-nav">
          <li id="first"><a><</a></li>
          <li id="last"><a>></a></li>
        </ul> -->
        <ul class="pagination"> 
        </ul>
      </div>
  ');
} 


