; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.33"

; Modules
projects[backup_migrate][version] = "3.0"

projects[ctools][version] = "1.4"

projects[ckeditor][version] = "1.16"

projects[clean_markup][version] = "2.7"

projects[compass][version] = "1.0-beta1"

projects[crumbs][version] = "2.2"

projects[facetapi][version] = "1.5"

projects[date][version] = "2.8"

projects[ds][version] = "2.7"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[google_analytics][version] = "2.0"

projects[inline_entity_form][version] = "1.5"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[menu_breadcrumb][version] = "1.5"

projects[pathauto][version] = "1.2"

projects[services][version] = "3.11"

projects[rules][version] = "2.7"

projects[search_api][version] = "1.13"

projects[simplenews][version] = "1.1"

projects[tablefield][version] = "2.3"

projects[token][version] = "1.5"

projects[views][version] = "3.8"

projects[views_accordion][version] = "1.0"

projects[views_slideshow][version] = "3.1"

projects[webform][version] = "4.1"

projects[zurb_responsive_tables][version] = "1.x-dev"

; Themes
projects[basic][version] = "4.1"

projects[nucleus][subdir] = "nucleus"
projects[nucleus][version] = "1.5"

projects[zen][version] = "5.5"

projects[zurb_foundation][version] = "4.1"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fieldblock][download][type] = "git"
projects[fieldblock][download][url] = "http://git.drupal.org/project/fieldblock.git"
projects[fieldblock][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[program][download][type] = "git"
projects[program][download][url] = "https://github.com/nwpointer/geostudyabroadprogramsmodule.git"
projects[program][type] = "module"

projects[taxonomy_display][type] = "module"
projects[taxonomy_display][download][type] = "git"
projects[taxonomy_display][download][url] = "http://git.drupal.org/project/taxonomy_display.git"
projects[taxonomy_display][download][branch] = "7.x-1.x"
projects[taxonomy_display][download][revision] = "bf8d618697db63e335ed812b475c0bea5c72998c"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[basic][download][type] = "git"
projects[basic][download][url] = "https://github.com/nwpointer/geostudyabroadtheme.git"
projects[basic][type] = "theme"

